"""add_monedas_metodo_pago_and_factura_new_fields

Revision ID: 3f31a0f57845
Revises: 9b2c1d4e5f60
Create Date: 2026-05-06 20:09:44.421613

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3f31a0f57845"
down_revision = "9b2c1d4e5f60"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metodo_pago",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_index(op.f("ix_metodo_pago_id"), "metodo_pago", ["id"], unique=False)
    op.create_table(
        "monedas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("simbolo", sa.String(), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_index(op.f("ix_monedas_id"), "monedas", ["id"], unique=False)
    op.execute(
        """
        INSERT INTO monedas (id, nombre, simbolo, activo)
        VALUES
            (1, 'Peso Dominicano', 'RD$', true),
            (2, 'Dólar', '$', true)
        """
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('monedas', 'id'), (SELECT MAX(id) FROM monedas))"
    )
    op.execute(
        """
        INSERT INTO metodo_pago (id, nombre, activo)
        VALUES
            (1, 'Efectivo', true),
            (2, 'Tarjeta', true),
            (3, 'Transferencia', true)
        """
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('metodo_pago', 'id'), (SELECT MAX(id) FROM metodo_pago))"
    )
    op.add_column(
        "facturas",
        sa.Column(
            "id_moneda", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
    )
    op.add_column(
        "facturas",
        sa.Column(
            "id_metodo_pago", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
    )
    op.add_column(
        "facturas",
        sa.Column(
            "descuento", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
    )
    op.create_foreign_key(None, "facturas", "monedas", ["id_moneda"], ["id"])
    op.create_foreign_key(None, "facturas", "metodo_pago", ["id_metodo_pago"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "facturas", type_="foreignkey")
    op.drop_constraint(None, "facturas", type_="foreignkey")
    op.drop_column("facturas", "descuento")
    op.drop_column("facturas", "id_metodo_pago")
    op.drop_column("facturas", "id_moneda")
    op.drop_index(op.f("ix_monedas_id"), table_name="monedas")
    op.drop_table("monedas")
    op.drop_index(op.f("ix_metodo_pago_id"), table_name="metodo_pago")
    op.drop_table("metodo_pago")
    # ### end Alembic commands ###
