"""add icon_img to productos and categorias

Revision ID: 6ee282a26116
Revises: fffaba5f0404
Create Date: 2026-05-08 21:29:37.425436

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6ee282a26116'
down_revision = 'fffaba5f0404'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('icon_img', sa.String(length=100), nullable=True))
    op.add_column('productos', sa.Column('icon_img', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'icon_img')
    op.drop_column('categorias', 'icon_img')
    # ### end Alembic commands ###
