"""refactor_factura_structure_with_calculated_fields

Revision ID: f678644826b1
Revises: 3f31a0f57845
Create Date: 2026-05-06 21:25:52.479172

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f678644826b1"
down_revision = "3f31a0f57845"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to factura_detalles as nullable first
    op.add_column(
        "factura_detalles",
        sa.Column("descuento", sa.Float(), server_default=sa.text("0"), nullable=True),
    )
    op.add_column(
        "factura_detalles", sa.Column("base_imponible", sa.Float(), nullable=True)
    )
    op.add_column(
        "factura_detalles",
        sa.Column("itbis", sa.Float(), server_default=sa.text("0"), nullable=True),
    )
    op.add_column(
        "factura_detalles",
        sa.Column(
            "itbis_aplicado", sa.Float(), server_default=sa.text("0"), nullable=True
        ),
    )
    op.add_column(
        "factura_detalles", sa.Column("total_linea", sa.Float(), nullable=True)
    )

    # Change precio_unitario type
    op.alter_column(
        "factura_detalles",
        "precio_unitario",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )

    # Populate new columns for existing rows
    op.execute(
        """
        UPDATE factura_detalles
        SET
            descuento = COALESCE(descuento, 0),
            base_imponible = precio_unitario * cantidad,
            itbis = COALESCE(itbis, 0),
            itbis_aplicado = 0,
            total_linea = precio_unitario * cantidad
        """
    )

    # Now make columns NOT NULL
    op.alter_column("factura_detalles", "descuento", nullable=False)
    op.alter_column("factura_detalles", "base_imponible", nullable=False)
    op.alter_column("factura_detalles", "itbis", nullable=False)
    op.alter_column("factura_detalles", "itbis_aplicado", nullable=False)
    op.alter_column("factura_detalles", "total_linea", nullable=False)

    # Add new columns to facturas as nullable first
    op.add_column("facturas", sa.Column("subtotal", sa.Float(), nullable=True))
    op.add_column(
        "facturas",
        sa.Column(
            "porcentaje_descuento",
            sa.Float(),
            server_default=sa.text("0"),
            nullable=True,
        ),
    )
    op.add_column(
        "facturas",
        sa.Column("itbis", sa.Float(), server_default=sa.text("0"), nullable=True),
    )
    op.add_column("facturas", sa.Column("total_general", sa.Float(), nullable=True))

    # Populate new columns for existing rows
    op.execute(
        """
        UPDATE facturas
        SET
            subtotal = total,
            porcentaje_descuento = 0,
            descuento = COALESCE(descuento, 0),
            itbis = 0,
            total_general = total
        """
    )

    # Now make columns NOT NULL
    op.alter_column("facturas", "subtotal", nullable=False)
    op.alter_column("facturas", "porcentaje_descuento", nullable=False)
    op.alter_column("facturas", "itbis", nullable=False)
    op.alter_column("facturas", "total_general", nullable=False)

    # Alter existing descuento column type
    op.alter_column(
        "facturas",
        "descuento",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
        existing_server_default="0",
    )

    # Drop old total column
    op.drop_column("facturas", "total")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "facturas",
        sa.Column("total", sa.INTEGER(), autoincrement=False, nullable=True),
    )

    # Migrate data back
    op.execute("UPDATE facturas SET total = total_general WHERE total IS NULL")

    op.alter_column(
        "facturas",
        "total",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        nullable=False,
    )

    op.alter_column(
        "facturas",
        "descuento",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default="0",
    )
    op.drop_column("facturas", "total_general")
    op.drop_column("facturas", "itbis")
    op.drop_column("facturas", "porcentaje_descuento")
    op.drop_column("facturas", "subtotal")
    op.alter_column(
        "factura_detalles",
        "precio_unitario",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("factura_detalles", "total_linea")
    op.drop_column("factura_detalles", "itbis_aplicado")
    op.drop_column("factura_detalles", "itbis")
    op.drop_column("factura_detalles", "base_imponible")
    op.drop_column("factura_detalles", "descuento")
    # ### end Alembic commands ###
